### ISSUE TITLE
The eslint rule can't  detect mixture tabs and spaces.

### ISSUE THREAD

**Issue by kenshinji** [Wiredcraft/eslint-config-wcl-backend#10]
Refer to this issue https://github.com/starbucks-china/user-preference/issues/6#issuecomment-391923124

**Comment by kenshinji** [comment]
In general, if we use following configuration then it will disallow mixing tabs and spaces, according to [this](https://eslint.org/docs/rules/no-mixed-spaces-and-tabs).
`"extends": "eslint:recommended"`

We've added this configuration since `v0.2.2`, however it haven't been released to npm.

**Comment by xavierchow** [comment]
we moved to prettier for the formatting issue: https://prettier.io/docs/en/comparison.html,
closing.
