### ISSUE TITLE
v0.2.2 can't detect a few lint errors which could be detected in v0.2.1

### ISSUE THREAD

**Issue by kenshinji** [Wiredcraft/eslint-config-wcl-backend#12]
Please refer to [this](https://github.com/starbucks-china/user-preference/issues/15)

**Comment by paulvollmer** [comment]
we added `eslint:recommended` to the extends list. this could be the reason..

https://github.com/Wiredcraft/eslint-config-wcl-backend/blob/cd74be04dc3f23e10f9c6db5a48c20f9a1843053/lint.json#L7-L10

**Comment by kenshinji** [comment]
@paulvollmer yeah, I think so, removing `eslint:recommended` definitely could solve our problem. One step further, do you think we need to find which rules are conflict with our previous version(`v0.2.1`) ?@xavierchow

**Comment by kenshinji** [comment]
I did some research and find out the way @paulvollmer adding `eslint:recommended` is actually to override the rules in `loopback` with these from `eslint:recommended`. So if we need to keep these rules from `loopback` even if conflict one is found from `eslint:recommended`, all we have to do is to switch the order of these two imported configurations like below. @xavierchow  what do you say?

```
 "extends": [ 
   "eslint:recommended" ,
   "loopback"
 ]
```

**Comment by xavierchow** [comment]
What's the difference between both extends and only loopback?
you can use `eslint --print-config` to figure it out I guess.

**Comment by kenshinji** [comment]
@xavierchow yeah, I exported these two versions of rules, and have a diff online you can checkout from [here](
https://www.diffchecker.com/0ey8I8jM). There are more than 150+ removals and additions. I think we'd better have a discussion before we made the decision. 

[v0.2.1.config.txt](https://github.com/Wiredcraft/eslint-config-wcl-backend/files/2208004/v0.2.1.config.txt)
[v0.2.2.config.txt](https://github.com/Wiredcraft/eslint-config-wcl-backend/files/2208005/v0.2.2.config.txt)

And @paulvollmer could you please elaborate the reason that why you added `eslint:recommened`, maybe we just need part of rules from it?

**Comment by xavierchow** [comment]
Hmm, too many diffes, I don't remember why eslint:recomended was added, shall we remove it?

**Comment by paulvollmer** [comment]
@xavierchow it was added to lint unused variables. we can remove eslint:recommend and add a rule to check unused variables

**Comment by kenshinji** [comment]
@paulvollmer agreed, that's the right we approach this problem, IMHO. What do you say? @xavierchow

**Comment by xavierchow** [comment]
@kenshinji agreed, pls remove the eslint:recommend and add specific rules needed separately.

**Comment by kenshinji** [comment]
@xavierchow Do we need to step further to release a new version since we've merged the PR?

**Comment by xavierchow** [comment]
0.3.0 published.

**Comment by xavierchow** [comment]
closing.
