### ISSUE TITLE
add no-return-await rule

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/eslint-config-wcl-backend#14]
https://eslint.org/docs/rules/no-return-await

**Comment by kenshinji** [comment]
@xavierchow  Should we fix this after we have a conclusion for [this issue](https://github.com/Wiredcraft/eslint-config-wcl-backend/issues/12)

**Comment by kenshinji** [comment]
Shall we set `no-return-await` to `error` or `warn`? @xavierchow

**Comment by xavierchow** [comment]
I think it's warn

**Comment by kenshinji** [comment]
merged, closing.
