### ISSUE TITLE
Adding 'no-unused-vars' to the rules

### ISSUE THREAD

**Issue by paulvollmer** [Wiredcraft/eslint-config-wcl-backend#7]
Let us add the rule `no-unused-vars` https://eslint.org/docs/rules/no-unused-vars to the config to detect unused variables in our codebase.

/cc @makara @JuhaS

**Comment by makara** [comment]
Yeah it can be useful but I'd say keep it as a warning. Also

> The "extends": "eslint:recommended" property in a configuration file enables this rule.

I wonder why we are not using `eslint:recommended`?

**Comment by xavierchow** [comment]
sure, can you send a PR?

**Comment by paulvollmer** [comment]
i'm for `eslint:recommended`. i'll add this to our config and set it as `warn`

**Comment by paulvollmer** [comment]
@xavierchow @makara PR is out: https://github.com/Wiredcraft/eslint-config-wcl-backend/pull/8

**Comment by paulvollmer** [comment]
can we close the issue?

**Comment by xavierchow** [comment]
sure, closing.
